---
- name: Configure laptop
  hosts: tuxedo

  tasks:
    - name: Include common roles
      ansible.builtin.include_role:
        name: "{{ item.role }}"
        apply:
          tags: "{{ item.tags | default([]) }}"
      loop:
        - role: ansible-role-packages
          tags: packages
        - role: ceso.dotfiles
          tags: dotfiles
      loop_control:
        label: "{{ item.role }}"
      tags: common-roles

    - name: Set extra role vars
      ansible.builtin.set_fact:
        "{{ fact.key }}": "{{ fact.value }}"
      loop: >-
        {{ extra_roles | default([])
           | selectattr('vars', 'defined')
           | map(attribute='vars')
           | map('dict2items')
           | flatten }}
      loop_control:
        loop_var: fact
        label: "{{ fact.key }}"
      when: extra_roles is defined and extra_roles | length > 0
      tags: extra-roles

    - name: Include host specific roles
      ansible.builtin.include_role:
        name: "{{ item.role }}"
        apply:
          become: "{{ item.become | default(false) }}"
          tags: "{{ item.tags | default([]) }}"
      loop: "{{ extra_roles | default([]) }}"
      loop_control:
        label: "{{ item.role }}"
      when: extra_roles is defined and extra_roles | length > 0
      tags: extra-roles

    - name: Run ghostty-installer.sh script
      ansible.builtin.script:
        cmd: "{{ ansible_facts['user_dir'] }}/.local/bin/ghostty-installer.sh"
      register: ghostty_result
      changed_when: "'already installed and current' not in ghostty_result.stderr"
      tags: install-ghostty

